= Data4Life SDK
:link-repository: https://github.com/d4l-data4life/hc-sdk-kmp
:util-sdk-version: 1.15.1
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <!-- PROJECT LOGO -->
    <p>
        <a href="https://github.com/d4l-data4life/hc-sdk-kmp">
            <img src="assets/images/d4l-logo.svg" width="150"/>
        </a>
    <!-- PROJECT HEADER -->
    <h1>The Data4Life Android and Java SDK</h1>
    <p><!-- PROJECT DESCRIPTION -->
        This is the Android and Java SDK of Data4Life.The SDK encapsulates the backend functionality of the Data4Life Personal Health Data Platform (PHDP) and enables end-to-end encryption of patient data.It allows users to store sensitive health data on the secure platform and share it to authorized people and applications.

For more information about the platform, visit our website <a href="https://www.d4l.io/">www.d4l.io</a>.
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="https://github.com/d4l-data4life/hc-sdk-kmp"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/d4l-data4life/hc-sdk-kmp/issues">Report Bug</a>
        ·
        <a href="https://github.com/d4l-data4life/hc-sdk-kmp/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <a href="https://github.com/d4l-data4life/hc-sdk-kmp/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>
        <a href="https://github.com/d4l-data4life/hc-sdk-kmp/actions">
            <img src="https://github.com/d4l-data4life/hc-sdk-kmp/actions/workflows/d4l-ci-latest-version.yml/badge.svg" alt="D4L CI - Latest Version"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents
toc::[]


== Documentation

For the current documentation, see link:https://www.d4l.io/[documentation]


== Before you start

To use the Data4Life SDK, you must obtain a partner ID from Data4Life. To receive a partner ID, get in touch with us at contact@data4life.care.

If you just want to explore the SDK you'll find a test configuration in `sample-android` or `sample-java` to start with.

=== Software requirements

* Android 6.0 (API 23) to Android 11 (API 30)
* Kotlin 1.4.32
* Java 8 link:https://developer.android.com/studio/write/java8-support[Limitations] link:https://jakewharton.com/d8-library-desugaring/[Desugaring]
* Gradle6.9.1

=== Dependencies

The SDK has the following dependencies:

* link:https://github.com/square/retrofit[retrofit2]
* link:https://github.com/ReactiveX/RxJava[rxjava2]
* link:https://github.com/d4l-data4life/hc-fhir-sdk-java[D4L FHIR STU3]
* link:https://github.com/d4l-data4life/hc-auth-sdk-kmp/[Data4Life Auth]
* link:https://github.com/d4l-data4life/hc-crypto-sdk-kmp/[Data4Life Crypto]
* link:https://github.com/d4l-data4life/hc-securestore-sdk-kmp/[Data4Life Securestore]
* link:https://github.com/d4l-data4life/hc-result-sdk-kmp/[Data4Life Result]
* link:https://github.com/d4l-data4life/hc-util-sdk-kmp/[Data4Life Util]
* link:https://github.com/ThreeTen/threetenbp[ThreeTen Java 8 Time backport]
* link:http://bouncycastle.org/[BouncyCastle] *
* link:https://github.com/google/tink[Tink]
* link:https://github.com/openid/AppAuth-Android[AppAuth] **

**Notes:**

* The SDK ships with BouncyCastle 1.64 and will replace the BouncyCastle version provided by the Android system.Ensure that if you're using or depend on BouncyCastle CryptoProvider, you're still compatible. <br />
* The SDK ships with a forked version of the AppAuth lib which includes a compatibility fix for working with `androidx` libs and a synchronous token refresh call for better thread handling.


== Install Gradle

=== Setup maven repositories

Add the following maven repository url to your root build.gradle:

Please take a look over at Github https://docs.github.com/en/packages/publishing-and-managing-packages/about-github-packages#about-tokens[about-github-packages#tokens, window="_blank"] on how to generate your private token for accessing the Github Package Registry.
Add `gpr.user = {your Github username}` and `gpr.key = {private github access token}` to your `gradle.properties`

[source,gradle]
----
allprojects {
    repositories {
        ...
        maven("https://jitpack.io")
        maven {
            url = uri("https://maven.pkg.github.com/d4l-data4life/hc-util-sdk-kmp")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
            }
        }
        maven {
            url = uri("https://maven.pkg.github.com/d4l-data4life/hc-fhir-sdk-java")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
            }
        }
        maven {
            url = uri("https://maven.pkg.github.com/d4l-data4life/hc-fhir-helper-sdk-kmp")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
            }
        }
    }
}
----

Your GitHub **username** and **token** needs to be stored in your global Gradle properties: `~/.gradle/gradle.properties`

NOTICE:: You need to have *read* access to this repository and generate a link:https://github.com/settings/tokens/new[personal access token] with `repo`, `write:packages` and `read:packages` scope.

----
gpr.user=github-username
gpr.key=github-token
----

==== Setup Maven Repository

We use GitHub Packages to distribute the SDK. In order to consume our dependencies you need to generate a GitHub Personal Access Token. Please follow the how to  link:https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#authenticating-to-github-packages[authenticate to GitHub Packages, window="_blank"].

NOTICE:: You need to have _read_ access to this repository and generate a https://github.com/settings/tokens/new/[personal access token] with `repo` and `read:packages` scope.

The token needs to be made available:

1. Add `gpr.user = {GitHub username}` and `gpr.key = {GitHub Personal Access Token}` to your global Gradle properties `~/.gradle/gradle.properties`

    ----
    gpr.user=github-username
    gpr.key=github-token
    ----

2. Or add following environment variables `PACKAGE_REGISTRY_USERNAME={GitHub username}` and `PACKAGE_REGISTRY_TOKEN={GitHub Personal Access Token}`

Then add the following maven repository configuration to your root build.gradle:

----

allprojects {
    repositories {
        ...
        maven {
            url = URI("https://maven.pkg.github.com/d4l-data4life/hc-fhir-sdk-kmp")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
            }
        }
    }
}

----

=== Java SDK dependency

Add the following dependencies to your app `build.gradle` file.

[source,gradle]
----
dependencies {
    implementation('care.data4life.hc-sdk-kmp:sdk-jvm:${latestVersion}') {
            exclude group: 'care.data4life.hc-sdk-kmp', module: 'securestore-android'
            exclude group: 'care.data4life.hc-sdk-kmp', module: 'crypto-android'
            exclude group: 'care.data4life.hc-sdk-kmp', module: 'auth-android'
            exclude group: 'care.data4life.hc-util-sdk-kmp', module: 'util-android'
            exclude group: 'care.data4life.hc-result-sdk-kmp', module: 'error-android'
    }
}
----

=== Android SDK dependency

[source,gradle]
----
dependencies {
    implementation('care.data4life.hc-sdk-kmp:sdk-android:${latestVersion}') {
        exclude group: 'care.data4life.hc-sdk-kmp', module: 'securestore-jvm'
        exclude group: 'care.data4life.hc-sdk-kmp', module: 'crypto-jvm'
        exclude group: 'care.data4life.hc-sdk-kmp', module: 'auth-jvm'
        exclude group: 'care.data4life.hc-util-sdk-kmp', module: 'util-jvm'
        exclude group: 'care.data4life.hc-result-sdk-kmp', module: 'error-jvm'
    }
}
----

The SDK is only published as release variant. So you need to add a `matchingFallbacks` config to all of your `buildTypes` and `flavors`. See link:https://developer.android.com/studio/build/dependencies#variant_aware[variant awareness] for more details.

[source, gradle]
----
android {
    buildTypes {
        debug {
            matchingFallbacks = ["release", "debug"]
        }
    }
}
----

The SDK ships with link:https://github.com/ThreeTen/threetenbp[ThreeTenBP] a Java 8 Time backport. For Android, its loading mechanism of time zone information is inefficient.So we recommend to provide your favorite Android ThreeTen library here, for example link:https://github.com/JakeWharton/ThreeTenABP[ThreeTenABP].

[source,gradle]
----
dependencies {
    implementation("care.data4life.hc-sdk-kmp:sdk-android:${latestVersion}") {
        ...
        // exclude the threetenbp dependency from the `sdk`
        exclude group: 'org.threeten', module: 'threetenbp'
    }
    // provide your favorite ThreeTen library here
    implementation 'com.jakewharton.threetenabp:threetenabp:1.2.2'
}
----

To ensure Java 8 compatibility, add compile options to app `build.gradle`:

[source,gradle]
----
android {
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}
----

=== Client configuration
After all the maven repositories and gradle dependencies are setup, the client needs to pass the configuration information to the SDK during initialization.

==== Android
On Android side the client can set manifest placeholder in their `build.gradle` to pass the configuration to the SDK.

[source,gradle,bulid.gradle]
----
// build.gradle

android {
    defaultConfig {
        manifestPlaceholders = mapOf<String, Any>(
            "clientId" to "CLIENT_ID",
            "clientSecret" to "CLIENT_SECRET",
            "redirectScheme" to "REDIRECT_SCHEME",
            "environment" to "ENVIRONMENT",
            "platform" to "D4L",
            "debug" to "false"
        )
        ...
    }
}

----

==== Java

On Java side the client config will be passed as arguments to the `init` function.

[source,java]
----
Data4LifeClient.init("userAlias",
                    "CLIENT_ID",
                    "CLIENT_SECRET",
                    Environment.PRODUCTION,
                    "REDIRECT_SCHEME",
                    "D4L");
----

== Building and Working with the SDK

There are several requirements for building the SDK.

=== Requirements

* Android 6.0 (API 23) to Android 11 (API 30)
* Kotlin 1.4.32
* Java 8 link:https://developer.android.com/studio/write/java8-support[Limitations] link:https://jakewharton.com/d8-library-desugaring/[Desugaring]
* Gradle 6.8.3
* link:https://developer.android.com/studio#downloads[Android Studio 4.2.2]
* Android Emulator 23 - 30

**Note:** Disable Instant Run in Android Studio, or the project fails to compile.

=== Config files

Before you can start to compile the SDK you need to add `d4l-client-config-android.json` and `d4l-test-config-android.json` files in the project root folder and add following content.

`d4l-client-config-android.json` needs to contain a config for every environment LOCAL, DEVELOPMENT, STAGING, SANDBOX, PRODUCTION.

NOTE: The CI expects this configuration from environment variables stored in GitHub secrets: `D4L_CLIENT_CONFIG_ANDROID` and `D4L_CLIENT_CONFIG_IOS`

[source,json,d4l-client-config-android.json]
----
// d4l-client-config-android.json
{
  "platform": "d4l",
  "configs": {
    "LOCAL": {
      "id": "{CLIENT_ID}",
      "secret": "{CLIENT_SECRET}",
      "redirectScheme": "{CLIENT_REDIRECT_SCHEME}"
    },
    "DEVELOPMENT": {
      "id": "{CLIENT_ID}",
      "secret": "{CLIENT_SECRET}",
      "redirectScheme": "{CLIENT_REDIRECT_SCHEME}"
    }
  }
}
----

[source,json,d4l-test-config-android.json]
----
// d4l-test-config-android.json
{
  "user": {
    "email": "{USER_EMAIL}",
    "password": "{USER_PASSWORD}",
    "phoneCountryCode": "{USER_PHONE_COUNTRY_CODE}",
    "phoneLocalNumber": "{USER_PHONE_LOCAL_NUMBER}"
  },
  "twillio": {
    "accountSid": "{TWILLIO_ACCOUNT_SID}",
    "authSid": "{TWILLIO_AUTH_SID}",
    "authToken": "{TWILLIO_AUTH_TOKEN}"
  }
}
----

To provide the test config to the different modules run the following gradle task in the root directory of the project.
[source,bash]
----
./gradlew provideTestConfig
----


=== SDK

==== Releasing the SDK

For release management, we use link:https://help.github.com/articles/creating-releases/[GitHub Releases].So just create a new release, set the tag according to link:https://semver.org/[Semantic Versioning] and publish.

===== Java

[source,gradle]
----
dependencies {
    implementation("care.data4life.hc-sdk-kmp:sdk-jvm:{latestCommitHashOnMain}") {
        ...
    }
}
----

===== Android

[source,gradle]
----
dependencies {
    implementation("care.data4life.hc-sdk-kmp:sdk-android:{latestCommitHashOnMain}") {
        ...
    }
}
----

==== Maintainer
Certificate pinning is done by providing a set of certificates by hash of the public key. To get the hash from certificate use the following:

[source,bash]
----
openssl x509 -inform der -in sandbox.hpihc.de.cer -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
----

==== Certificate Pin
To get the Base64 encoded sha256 of the HTTPS public key pinning use the following command in the terminal

[source,bash]
----
openssl s_client -servername api.data4life.care -connect app.data4life.care:443 | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
----
See link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning[HTTP Public Key Pinning] for more information.


=== About Data4Life documentation
We use link:https://asciidoctor.org/[AsciiDoctor], a fast, open source text processor and publishing toolchain for converting AsciiDoc content to HTML5, DocBook, PDF, and other formats.In this case HTML5.

To build the project documentation we use the link:https://github.com/asciidoctor/asciidoctor-gradle-plugin[Asciidoctor Gradle Plugin] that fits our Gradle build chain.

Additionally, we use the link:https://github.com/asciidoctor/asciidoctor-diagram[AsciiDoctor Diagramm extension] which adds support for BlockDiag (BlockDiag, SeqDiag, ActDiag, NwDiag), Ditaa, Erd, GraphViz, Mermaid, Msc, PlantUML, Shaape, SvgBob, Syntrax, UMLet, Vega, Vega-Lite and WaveDrom.

==== Documentation structure
The base for the documentation is located in the `sdk-doc` module.It's main purpose is to configure Asciidoctor and define the style and distribution.
You will find a `index.adoc` under `sdk-doc/src/docs/asciidoc` which is used to include documentation of other modules in one single book documentation.

Every project module has a `{module-name}/src/docs/asciidoc` folder where all documentation files will be located.So every module will host it's own documentation.

==== Generating the documentation
To generate the latest documentation just call `./gradlew asciidoctor` this will build the `sdk-doc` module and replace the documentation for the current SDK version in the `docs` folder.
