// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

== Authorization Code Grant

[plantuml, pin-code-grant ,svg]
--
skinparam Shadowing false
skinparam sequenceArrowThickness 1
skinparam maxmessagesize 120
skinparam ParticipantPadding 10
autonumber

actor "Broker User\n(Charité Patient)" as User
participant Broker

box "Authorization Service \n(lives in Terra)"
participant "Auth Frontent\n(Luna)" as Frontend
participant "Auth Backend\n(Vega)" as Backend
end box

participant "Web App\n(Terra)" as WebApp

title Code Authorization Flow

User -> Broker: Connection Request
activate Broker
Broker -> Broker: initialize SDK
activate Broker #Yellow
Broker -> Broker: generate Authorization Url
deactivate Broker
Broker -> Frontend: Authentication Request
deactivate Broker
activate Frontend
Frontend -> Frontend: render page
User -> Frontend: Enters credentials: email, password, pin

Frontend -> Broker: verify pin
activate Broker
Broker -> Frontend: verify response
deactivate Broker

Frontend -> Backend: login/register
activate Backend
Backend -> Frontend: login response
Frontend -> Backend: approve
deactivate Frontend
Backend -> Broker: Authentication Response
deactivate Backend
activate Broker
Broker -> Broker: restore state
Broker -> Broker: initialize SDK
activate Broker #Yellow
deactivate Broker
Broker -> WebApp: redirect
deactivate Broker
activate WebApp
WebApp -> WebApp: trigger notification

deactivate WebApp

--
