// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:
// Variables:
:icons: font
:toc:
:compname-short: D4L
:compname-legal: D4L data4life gGmbH
:compname: Data4Life
:email-contact: contact@data4life.care
:email-docs: docs@data4life.care
:url-company: https://www.data4life.care
:url-docs: https://d4l.io
:prod-name: Data4Life
:app-name: Data4Life
:app-plat: Android
:phdp-plat: Personal Health Data Platform
:sw-name: {compname} {prod-name}
:sw-version: 1.7.0
:pub-type: Internal 
:pub-version: 1.00
:pub-status: draft
:pub-title: {software-name} {pub-type}
:copyright-year: 2020
:copyright-statement: (C) {copyright-year} {compname-legal}. All rights reserved.


= Authorization documentation

ifndef::sourcedir[:sourcedir: ../kotlin]

This section covers the authorization project features of the SDK. Authentication is the process of verifying who a user is, while authorization is the process of verifying what they have access to.


== Starting authorization requests
The authorization request is started with the following code sample which launches an `Activity`
to present the login screen to the user for authentication.

[source,java]
-----
Intent authIntent = Data4LifeClient.getInstance().getLoginIntent(MainActivity.this, null);
startActivityForResult(authIntent, requestCode);
-----

You can pass along optional `scopes`, otherwise the SDK uses the default scopes for the authorization
request.

== Ending authorization requests
Once the user is logged in, canceled the authorization request, or if an exception occured during the authentication process, the SDK sends the response to the integrator application  in the `onActivityResult(…)` method. The authorization results can be the following: 

- `Activity.RESULT_OK` – when the login is successful.
- `Activity.RESULT_CANCELED` – when the login fails, with additional payload in `data`, as shown in the example.

[source,java]
----
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (requestCode == GC_AUTH) {
        if (resultCode == RESULT_OK) {
            loggedIn();
        } else if (data.getExtras() != null) {
            if (data.getExtras().containsKey("error")) {
                Snackbar.make(mRootCL, "Failed to log in to Data4Life", Snackbar.LENGTH_SHORT).show();
            } else if (data.getExtras().containsKey("canceled")) {
                Snackbar.make(mRootCL, "User canceled authorization request", Snackbar.LENGTH_SHORT).show();
            }
        }
    }
}
----


include::authorization_code_grant.adoc[]

