// Settings:
:toc:
:doctype: book
:icons: font
:source-highlighter: prettify
:stylesdir: ..
:imagesdir: images/
:linkcss:
:setanchors:
:sectanchors:
:setlinks:
:sectlinks:

// Variables:
:compname-short: D4L
:compname-legal: D4L data4life gGmbH
:compname: Data4Life
:email-contact: we@data4life.care
:email-docs: docs@data4life.care
:url-company: https://www.data4life.care
:url-docs: https://d4l.io
:prod-name: Data4Life
:app-plat: Android/Java
:phdp-plat: Personal Health Data Platform (PHDP)
:sw-name: {compname} {prod-name}
:sw-version: 1.30
:pub-type: Internal
:pub-version: 1.00
:pub-status: draft
:pub-title: {sw-name} {pub-type}
:copyright-year: 2019-2022
:copyright-statement: (C) {copyright-year} {compname-legal}. All rights reserved.

= Using the {app-plat} SDK

== About the Project

This is the {app-plat} SDK of Data4Life. The SDK encapsulates the backend functionality of the {prod-name} Personal Health Data Platform (PHDP) and enables end-to-end encryption of health data. It allows users to store and access sensitive data on the secure platform and share it to authorized users and applications.

For more information about the {prod-name} platform, visit our http://www.data4life.care/[website].

=== Features

* Authorization/Authentication
* End-to-End encryption
* API client for PHDP
* Data types support for custom, FHIR 3 and FHIR 4

=== Build with

* link:https://kotlinlang.org/docs/reference/mpp-intro.html[Kotlin Multiplatform]
* link:https://github.com/square/retrofit[retrofit2]
* link:https://github.com/ReactiveX/RxJava[rxjava2]
* link:https://github.com/d4l-data4life/hc-fhir-sdk-java[D4L FHIR STU3 and R4]
* link:https://github.com/d4l-data4life/hc-auth-sdk-kmp/[Data4Life Auth]
* link:https://github.com/d4l-data4life/hc-crypto-sdk-kmp/[Data4Life Crypto]
* link:https://github.com/d4l-data4life/hc-securestore-sdk-kmp/[Data4Life Securestore]
* link:https://github.com/d4l-data4life/hc-result-sdk-kmp/[Data4Life Result]
* link:https://github.com/d4l-data4life/hc-util-sdk-kmp/[Data4Life Util]
* link:https://github.com/ThreeTen/threetenbp[ThreeTen Java 8 Time backport]
* link:http://bouncycastle.org/[BouncyCastle] *
* link:https://github.com/google/tink[Tink]
* link:https://github.com/openid/AppAuth-Android[AppAuth]

**Notes:**

* The SDK ships with BouncyCastle and will replace the BouncyCastle version provided by the Android system. Ensure that if you're using or depend on BouncyCastle CryptoProvider, you're still compatible.

== Before you start

To use the SDK, you must have a {prod-name} *partner ID*. To obtain a partner ID, get in touch with us at {email-contact}.

== Getting started

Once you have a partner ID, follow these steps to start working with the SDK:

=== Software requirements

* Android 6.0 (API 23) to Android 11 (API 30)
* Java 8 link:https://developer.android.com/studio/write/java8-support[Limitations] link:https://jakewharton.com/d8-library-desugaring/[Desugaring]
* Kotlin 1.4.32

== Installation

=== Consume GitHub Packages

We use GitHub Packages to distribute the SDK. In order to consume our dependencies you need to generate a GitHub Personal Access Token. Please follow the how to link:https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#authenticating-to-github-packages[authenticate to GitHub Packages, window="_blank"].

NOTICE:: You need to have _read_ access to this repository and generate a https://github.com/settings/tokens/new/[personal access token, window="_blank"] with `repo` and `read:packages` scope.

==== GitHub Token

The token needs to be made available.

. Add `gpr.user = {GitHub username}` and `gpr.key = {GitHub Personal Access Token}` to your global Gradle properties `~/.gradle/gradle.properties`
+
[source,bash]
----
gpr.user=github-username
gpr.key=github-token
----

. Or add following environment variables `PACKAGE_REGISTRY_USERNAME={GitHub username}` and `PACKAGE_REGISTRY_TOKEN={GitHub Personal Access Token}`

==== Setup Maven Repository

Add the following maven repository configuration to your root `build.gradle/build.gradle.kts`:

.Gradle KTS
[%collapsible%open]
====
[source,kotlin]
----
allprojects {
    repositories {
        ...
        maven {
            url = uri("https://maven.pkg.github.com/d4l-data4life/hc-sdk-kmp")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
            }
        }
    }
}
----
====

.Gradle Groovy
[%collapsible]
====
[source,groovy]
----
allprojects {
    repositories {
        ...
        maven {
            url = uri("https://maven.pkg.github.com/d4l-data4life/hc-sdk-kmp")
            credentials {
                username = project.findProperty("gpr.user") as ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                password = project.findProperty("gpr.key") as ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
            }
        }
    }
}
----
====

=== Android SDK dependency

[source,kotlin]
----
dependencies {
    implementation("care.data4life.hc-sdk-kmp:sdk-android:LATEST_VERSION")
}
----

The SDK ships with link:https://github.com/ThreeTen/threetenbp[ThreeTenBP] a Java 8 Time backport. For Android, its loading mechanism of time zone information is inefficient. So we recommend providing your favorite Android ThreeTen library here, for example link:https://github.com/JakeWharton/ThreeTenABP[ThreeTenABP].

[source,kotlin]
----
dependencies {
    implementation("care.data4life.hc-sdk-kmp:sdk-android:LATEST_VERSION") {
        ...
        // exclude the threetenbp dependency from the `sdk`
        exclude group: "org.threeten", module: "threetenbp"
    }
    // provide your favorite ThreeTen library here
    implementation "com.jakewharton.threetenabp:threetenabp:1.4.0"
}
----

==== Configuration

The SDK is only published as release variant. So you need to add a `matchingFallbacks` config to all of your `buildTypes` and `flavors`. See link:https://developer.android.com/studio/build/dependencies#variant_aware[variant awareness] for more details.

[source,kotlin]
----
android {
    buildTypes {
        debug {
            matchingFallbacks = ["release", "debug"]
        }
    }
}
----

To ensure Java 8 compatibility, add compile options to app `build.gradle/build.gradle.kts`:

[source,kotlin]
----
android {
    compileOptions {
        sourceCompatibility = "1.8"
        targetCompatibility = "1.8"
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}
----

=== Java SDK dependency

Add the following dependencies to your app `build.gradle/build.gradle.kts` file.

[source,kotlin]
----
dependencies {
    implementation("care.data4life.hc-sdk-kmp:sdk-jvm:LATEST_VERSION")
}
----

==== Configuration

To ensure Java 8 compatibility, add compile options to app `build.gradle/build.gradle.kts`:

[source,kotlin]
----
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
----

== Usage

=== Android

On Android manifest placeholders are used to pass the configuration to the SDK.

. Add the `manifestPlaceholders` property with the `platform`, `environment`, `clientId`, `clientSecret`, and `redirectScheme` keys to your _build.gradle/build.gradle.kts_ file.
+
.Gradle KTS
[%collapsible%open]
====
[source,kotlin]
----
android {
    defaultConfig {
        manifestPlaceholders(mapOf(
                "platform" to "D4L",
                "environment" to "production",
                "clientId" to "clientId",
                "clientSecret" to "clientSecret",
                "redirectScheme" to "com.example",
                "debug" to "true"
        ))
    }
}
----
====
+
.Gradle Groovy
[%collapsible]
====
[source,groovy]
----
android {
    defaultConfig {
        manifestPlaceholders = [
            platform      : "D4L",
            environment   : "production",
            clientId      : "clientId",
            clientSecret  : "clientSecret",
            redirectScheme: "com.example",
            debug         : "false"
        ]
    }
}
----
====
+
NOTE: The `debug` flag is set to `false` if your app is not debuggable.


. To log in, use the `startActivityForResult` method with login intent.
+
[source,java]
----
Intent loginIntent = Data4LifeClient.getLoginIntent(context, null);
----
+
or with custom scopes
+
[source,java]
----
Intent loginIntent = Data4LifeClient.getLoginIntent(
    context,
    new String[] {"scope:r", "scope:w"}
);
----
+
and then
+
[source,java]
----
startActivityForResult(loginIntent, Data4LifeClient.D4L_AUTH);
----

. Handle the login result in your `onActivityResult` method.
+
[source,java]
----
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (requestCode == D4L_AUTH){
        if (resultCode == RESULT_OK){
            // you are now logged in
        }
    }
}
----

. Get the {compname} client instance inside Activity or Fragment.
+
[source,java]
----
Data4LifeClient client = Data4LifeClient.getInstance();
----

. Now you can use the available API for the 3 supported data types which will return results on background thread.

=== Java

The Java SDK only supports a single-user use case. For every individual user, the SDK must be instantiated with the user alias.

. Instantiate the client with `alias`, `platform`, `environment`, `clientId`, `clientSecret`, and `redirectUrl` properties:
+
[source,java]
----
Data4LifeClient client = Data4LifeClient.init(
    "alias",
    "clientId",
    "clientSecret",
    Environment.PRODUCTION,
    "redirectUrl",
    "platform"
);
----
+
NOTE: The `alias`  is used to namespace the session that is bound to a client instance. This allows multiple instances of the client running with different sessions in parallel. Could be used to bind a client instance to a user in a multiuser environment.

. To log in, you need start the OAuth 2.0 authorization flow by generating the authorization url and hand it over to a browser and let the user authorize.
+
[source,java]
----
String authorizationUrl = client.getAuthorizationUrl();
----

. After the browser auth session calls the previously registered `redirectUrl`, pass the received OAuth callback URL to the client instance
+
[source,java]
----
String callbackUrl = "https://.../oauth/callback?code=12345&state=abcde"
boolean authorized = client.finishLogin(callbackUrl);
----

. If you're in a multiuser setup with multiple SDK instances, you could extract the alias from the callbackUrl
+
[source,java]
----
UserIdExtractor extractor = new UserIdExtractor();
String userId = extractor.extract(callbackUrl);
----
+
NOTE: Multiple instance management is not handled by the SDK and needs to be done by you, e.g. with a Map<String,Data4LifeClient> or better suitable solution

. Now you can use the available API for the 3 supported data types which will return results on background thread.
