name: D4L CI - Pull-Request Precheck

on:
  pull_request:
    types: [opened, synchronize, edited, reopened, assigned, unassigned]
    branches:
      - main
      - release/*
      - feature/*

jobs:
  pull-request-precheck:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: danger/kotlin@1.0.0-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
