name: D4L CI - Label configuration

on: 
 pull_request:
   branches: 
     - main
     - feature/**
   paths:
     - '.github/labels.yml'

jobs:
  configure-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
