name: D4L CI - Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:

    runs-on: ubuntu-latest

    env:
      D4L_CLIENT_CONFIG_ANDROID: ${{ secrets.D4L_CLIENT_CONFIG_ANDROID }}
      D4L_TEST_CONFIG_ANDROID: ${{ secrets.D4L_TEST_CONFIG_ANDROID }}
      PACKAGE_REGISTRY_USERNAME: ${{ secrets.PACKAGE_REGISTRY_USERNAME }}
      PACKAGE_REGISTRY_TOKEN: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cleanup
        run: ./gradlew clean
      - name: Version
        run: ./gradlew versionInfo
      - name: Configure project
        run: ./gradlew provideTestConfig
      - name: Build project
        run: ./gradlew build
      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationToGitHubPackagesRepository
      - name: Publish Release to Maven Repo
        run: ./gradlew publishRelease
