name: D4L CI - Pull-Request Validation

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*
  workflow_dispatch:

jobs:
  pull-request-validation:

    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_DOWNLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_USERNAME }}
      PACKAGE_REGISTRY_DOWNLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_TOKEN }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Start emulator and wait for it
        run: ./script/ci/android/prepare_start_and_wait_for_emulator.sh
      - name: Install Chrome Browser
        run: adb install ./script/ci/android/com.android.chrome_79.0.3945.93-394509315-x86-nodpi.apk
      - name: Cleanup
        run: ./gradlew clean
      - name: Version
        run: ./gradlew versionInfo
      - name: Configure project
        run: ./gradlew provideTestConfig
      - name: Build
        run: ./gradlew build
      - name: Run sdk android tests
        run: ./gradlew :sdk-android:test
      - name: Run tests with code coverage
        run: ./gradlew jacocoTestReport
      - name: Publish Feature to Maven Repo
        run: ./gradlew publishFeature

