# Workflow to associate labels automatically
name: D4L CI - PR Labeler

on:
  - pull_request

jobs:
  add-labels-to-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
