name: D4L CI - Pull-Request Validation

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*
  workflow_dispatch:

jobs:
  pull-request-validation:

    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_DOWNLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_USERNAME }}
      PACKAGE_REGISTRY_DOWNLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_TOKEN }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Version
        run: ./gradlew versionInfo
      - name: Configure project
        run: ./gradlew provideTestConfig
      - name: Build
        run: ./gradlew build
      - name: Run SDK Android tests
        uses: reactivecircus/android-emulator-runner@v2.20.0
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -avd d4l-sdk -no-snapshot -no-audio -no-boot-anim -skin 768x1280 -camera-back none -camera-front none
          script: ./gradlew :sdk-android:test
      - name: Run tests with code coverage
        run: ./gradlew jacocoTestReport
      - name: Publish Feature to Maven Repo
        run: ./gradlew publishFeature

