name: D4L CI - Latest Version

on:
  push:
    branches:
      - main
      - release/*

jobs:
  latest-version:

    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_DOWNLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_USERNAME }}
      PACKAGE_REGISTRY_DOWNLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_TOKEN }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      D4L_CLIENT_CONFIG_ANDROID: ${{ secrets.D4L_CLIENT_CONFIG_ANDROID }}
      D4L_TEST_CONFIG_ANDROID: ${{ secrets.D4L_TEST_CONFIG_ANDROID }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Start emulator and wait for it
        run: ./script/ci/android/prepare_start_and_wait_for_emulator.sh
      - name: Install Chrome Browser
        run: adb install ./script/ci/android/com.android.chrome_79.0.3945.93-394509315-x86-nodpi.apk
      - name: Cleanup
        run: ./gradlew clean
      - name: Configure project
        run: ./gradlew provideTestConfig
      - name: Version
        run: ./gradlew versionInfo
      - name: Build
        run: ./gradlew build
      - name: Run sdk android tests
        run: ./gradlew :sdk-android:test
      - name: Run tests with code coverage
        run: ./gradlew jacocoTestReport
      - name: Publish Snapshot to Maven Repo
        run: ./gradlew publishSnapshot
