name: D4L CI - Latest Version

on:
  push:
    branches:
      - main
      - release/*

jobs:
  latest-version:

    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [ 30 ]

    env:
      PACKAGE_REGISTRY_DOWNLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_USERNAME }}
      PACKAGE_REGISTRY_DOWNLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_TOKEN }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      D4L_CLIENT_CONFIG_ANDROID: ${{ secrets.D4L_CLIENT_CONFIG_ANDROID }}
      D4L_TEST_CONFIG_ANDROID: ${{ secrets.D4L_TEST_CONFIG_ANDROID }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Configure project
        run: ./gradlew provideTestConfig
      - name: Version
        run: ./gradlew versionInfo
      - name: Build
        run: ./gradlew build
      - name: Run SDK Android tests
        uses: reactivecircus/android-emulator-runner@v2.23.0
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: Nexus 5
          force-avd-creation: false
          avd-name: d4l-sdk-${{ matrix.api-level }}
          emulator-options: -no-snapshot -no-audio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew --stacktrace :sdk-android:test
      - name: Run tests with code coverage
        run: ./gradlew jacocoTestReport
      - name: Publish Snapshot to Maven Repo
        run: ./gradlew publishSnapshot
